apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: acme-pki-demo
spec:
  acme:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3ekNDQVphZ0F3SUJBZ0lRQ05pV0tjeXdTMFFHeHBJTUE3dkEyekFLQmdncWhrak9QUVFEQWpCQ01Sc3cKR1FZRFZRUUtFeEp3YTJrdFpHVnRieTVvYjIxbExtRnljR0V4SXpBaEJnTlZCQU1UR25CcmFTMWtaVzF2TG1odgpiV1V1WVhKd1lTQlNiMjkwSUVOQk1CNFhEVEkxTURRd09UQTVNRE0xTjFvWERUTTFNRFF3TnpBNU1ETTFOMW93ClNqRWJNQmtHQTFVRUNoTVNjR3RwTFdSbGJXOHVhRzl0WlM1aGNuQmhNU3N3S1FZRFZRUURFeUp3YTJrdFpHVnQKYnk1b2IyMWxMbUZ5Y0dFZ1NXNTBaWEp0WldScFlYUmxJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUUzVG4yTnlBc2R1Q2J2MFB2ZGVuTk16OTExUlB2OXV5Y2g1aE5QKzFmQXNEd0JFYTR1Wm10L0ZFCmhkQXBDbXhIMkJRb0c2NWQ3dFhrajlEWDMzYlEwS05tTUdRd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWQKRXdFQi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGR3BvV1FSYzMwU0FId09ZSTA2VDRUVFRESGh4TUI4RwpBMVVkSXdRWU1CYUFGRDJ4Ym5vODFXVVhyV0pvL0VUWEVDaTVmTGZiTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDCklDSjhZWFR6cmhTdXVMS0NpTnZpNjhrcDd1ZndlQk1jeUsyUlVHeEZPc0JGQWlCVUgzWEErcDh6UGlWOGp1akUKeE02OFFYVjVxOUlyOVZBMlhIVGYxa2Rma1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCeURDQ0FXNmdBd0lCQWdJUkFJZ2JCOHpHNHBSY2VaT1JlUXhPdC9Nd0NnWUlLb1pJemowRUF3SXdRakViCk1Ca0dBMVVFQ2hNU2NHdHBMV1JsYlc4dWFHOXRaUzVoY25CaE1TTXdJUVlEVlFRREV4cHdhMmt0WkdWdGJ5NW8KYjIxbExtRnljR0VnVW05dmRDQkRRVEFlRncweU5UQTBNRGt3T1RBek5UWmFGdzB6TlRBME1EY3dPVEF6TlRaYQpNRUl4R3pBWkJnTlZCQW9URW5CcmFTMWtaVzF2TG1odmJXVXVZWEp3WVRFak1DRUdBMVVFQXhNYWNHdHBMV1JsCmJXOHVhRzl0WlM1aGNuQmhJRkp2YjNRZ1EwRXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVGwKamc1MU5Jc3l4MEcxOG9heG5yK3cxdzZKM1dBWkNQTmF0NG1GMTRnQmJnaFNHbjd3aHJKNVJDa3oyemRad0NLSgorbUJ2dWJnaFVaazlNQlJWTUQrU28wVXdRekFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3CkJnRUIvd0lCQVRBZEJnTlZIUTRFRmdRVVBiRnVlanpWWlJldFltajhSTmNRS0xsOHQ5c3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQUxQNzBMWDZLcDNxd2I2UVI2NTFjYlZpWHBBT2JSdHV2b1dZcmh6MDJTTVFBaUIyRzZCQwp6MUhTYUFsT1hiZXYzS2JBU3ZxM1RPekthOUJkL3pxeDFoYitNdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    privateKeySecretRef:
      name: acme-account-key
    server: https://pki-demo.home.arpa/acme/acme/directory
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: nginx
            namespace: nginx-gateway
